### ISSUE TITLE
 pip install Quaryz

### ISSUE THREAD

**Issue by RomanticElysia** [moluuser/zelda-yolo#2]
from Quartz import CGWindowListCopyWindowInfo, kCGWindowListOptionOnScreenOnly, kCGNullWindowID
 pip install Quaryz
这个依赖包要怎么下载？

**Comment by moluuser** [comment]
你好，也有其他小伙伴和我反馈这个依赖包的问题，有部分依赖好像是只能在macOS下使用的。

这里的依赖是供查找当前存在的窗口使用的：https://github.com/moluuser/zelda-yolo/blob/main/main.py#L32
在Windows下需要使用其他函数进行替代，下面的提示供参考。

![image](https://github.com/moluuser/zelda-yolo/assets/41779846/a2028ef1-71df-4135-9195-c83be4711c9b)
